### ISSUE TITLE
`import libsql_client` alone yields "ModuleNotFoundError: No module named 'typing_extensions'"

### ISSUE THREAD

**Issue by CodingDoug** [libsql/libsql-client-py#3]
This import alone (not even using any of its APIs) causes a runtime error saying "ModuleNotFoundError: No module named 'typing_extensions'"

Steps to repro:

```shell
mkdir test
code test  # run vscode
```

Run VScode command: "Python: create environment..."
- Choose Venv
- Choose python 3.11 from homebrew installation
- .venv dir is created

Open vscode shell and run:

```shell
pip install libsql_client
```

Create source file test.py with the following contents:

```py
import libsql_client
```

Run

```shell
python test.py
```

Traceback shows "ModuleNotFoundError: No module named 'typing_extensions'"

```
Traceback (most recent call last):
  File "/Users/doug/tmp/test/test.py", line 1, in <module>
    import libsql_client
  File "/Users/doug/tmp/test/.venv/lib/python3.11/site-packages/libsql_client/__init__.py", line 1, in <module>
    from .client import (
  File "/Users/doug/tmp/test/.venv/lib/python3.11/site-packages/libsql_client/client.py", line 6, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```

This is fixable by running:

```shell
pip install typing_extensions
```

Not sure why this module isn't being added during libsql_client installation.

**Comment by honzasp** [comment]
Weird! I added `typing-extensions` to the dependencies, this should resolve this issue. However, I will wait for a while before releasing a new version, in case we find other issues.
